plugins:
  - '@typescript-eslint'

extends:
  - airbnb-typescript/base
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:import/recommended
  - plugin:import/typescript

rules:
  no-new: off

parserOptions:
  project: ./tsconfig.json

ignorePatterns:
  - node_modules
  - '**/*.d.ts'
  - '**/*.js'

settings:
  'import/resolver':
    typescript:
      alwaysTryTypes: true
      
