AWSTemplateFormatVersion: "2010-09-09"

Description: Minecraft 'template-16a' server

Parameters:
  Environment:
    Type: String
    Description: Environment name will be appended to resource names
  NetworkStackName:
    Type: String
    Description: Name of the Minecraft VPC networking stack
  GameDataSnapshotId:
    Type: String
    AllowedPattern: "^snap-.*"
    Description: Snapshot ID to use when initializing the game server
  LaunchTemplateId:
    Type: String
    AllowedPattern: "^lt-.*"
    Description: Resource ID of the Minecraft EC2 launch template
  LaunchTemplateVersion:
    Type: Number
    Description: Version of the Minecraft EC2 launch template

Outputs:
  InstanceId:
    Description: Resource ID of the EC2 instance running the Minecraft game server
    Value: !Ref MinecraftServer
  VolumeId:
    Description: Resource ID of the EBS volume for the Minecraft game data
    Value: !Ref MinecraftGameData

Resources:
  MinecraftServer:
    Type: AWS::EC2::Instance
    Properties:
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplateId
        Version: !Ref LaunchTemplateVersion
      SubnetId:
        Fn::ImportValue: !Sub ${NetworkStackName}-subnet
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}

  MinecraftServerEIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref MinecraftServer
      Tags:
        - Key: Application
          Value: minecraft
        - Key: Environment
          Value: !Ref Environment
        - Key: Name
          Value: !Sub ${AWS::StackName}-address

  MinecraftGameData:
    Type: AWS::EC2::Volume
    DependsOn: MinecraftServer
    Properties:
      VolumeType: gp2
      SnapshotId: !Ref GameDataSnapshotId
      AvailabilityZone: !GetAtt MinecraftServer.AvailabilityZone
      Tags:
        - Key: Application
          Value: minecraft
        - Key: Environment
          Value: !Ref Environment
        - Key: Name
          Value: !Sub ${AWS::StackName}-data
