AWSTemplateFormatVersion: "2010-09-09"

Description: Launch templates for Minecraft EC2 servers

Parameters:
  Environment:
    Type: String
    Description: Environment name will be appended to resource names
  NetworkStackName:
    Type: String
    Description: Name of the Minecraft VPC networking stack
  SshKeyName:
    Type: String
    NoEcho: true
    Description: Key name for SSH access to EC2 servers
  MinecraftRconPassword:
    Type: String
    NoEcho: true
    Description: Password for the rcon remote execution protocol

Outputs:
  Template16aId:
    Description: Resource ID of the EC2 launch template for Minecraft version 1.16.x
    Value: !Ref MinecraftServer16aTemplate
  Template16aVersion:
    Description: Latest version of the EC2 launch template for Minecraft version 1.16.x
    Value: !GetAtt MinecraftServer16aTemplate.LatestVersionNumber

Resources:
  MinecraftServer16aTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Sub minecraft-${Environment}-16a-template
      LaunchTemplateData:
        ImageId: ami-0c3dda3deab25a563
        InstanceType: m6g.medium
        KeyName: !Ref SshKeyName
        SecurityGroupIds:
          - Fn::ImportValue: !Sub ${NetworkStackName}-sg
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: Application
                Value: minecraft
              - Key: Environment
                Value: !Ref Environment
        UserData:
          Fn::Base64: !Sub |
            #cloud-config
            packages:
              - java-11-amazon-corretto-headless
            package_update: true
            package_upgrade: true
            package_reboot_if_necessary: true

            runcmd:
              - sudo yum update --assumeyes
              - sudo yum upgrade --assumeyes
              - sudo mkdir /mnt/minecraft
              - sudo echo "/dev/sdm /mnt/minecraft xfs defaults,nofail 0 2" >> /etc/fstab
              - sudo systemctl enable minecraft.service

            write_files:
              - path: /home/ec2-user/config_server_props.sh
                permissions: '0755'
                content: |
                  #!/bin/sh -e

                  minecraft_dir=/mnt/minecraft
                  propfile_path=${!minecraft_dir}/server.properties
                  [ ! -f ${!propfile_path} ] && echo "" > ${!propfile_path}

                  set_property() {
                    prop=$1
                    value=$2
                    if [ ! `grep -R "^[#]*\s*${!prop}=.*" ${!propfile_path}` ]; then
                      echo ${!prop}=${!value} >> ${!propfile_path}
                    else
                      sed -i'' "s/^[#]*\s*${!prop}=.*/${!prop}=${!value}/" ${!propfile_path}
                    fi
                  }

                  set_property enable-rcon true
                  set_property rcon.password ${MinecraftRconPassword}
                  set_property white-list true
                  set_property enforce-whitelist true
                  set_property enable-command-block true
                  echo eula=true > ${!minecraft_dir}/eula.txt

              - path: /etc/systemd/system/minecraft.service
                content: |
                  [Unit]
                  Description=Minecraft game server
                  Requires=mnt-minecraft.mount
                  After=network.target

                  [Service]
                  Type=simple
                  User=ec2-user
                  WorkingDirectory=/mnt/minecraft
                  ExecStartPre=/usr/bin/sudo /usr/bin/chown ec2-user:ec2-user /mnt/minecraft
                  ExecStartPre=/usr/bin/wget https://papermc.io/api/v2/projects/paper/versions/1.16.5/builds/526/downloads/paper-1.16.5-526.jar -O minecraft.jar
                  ExecStartPre=/home/ec2-user/config_server_props.sh
                  ExecStart=/usr/bin/java -Xms2G -Xmx2G -jar minecraft.jar --noconsole
                  Restart=always
                  StartLimitIntervalSec=30
                  StartLimitBurst=1
                  SuccessExitStatus=0 143

                  [Install]
                  WantedBy=multi-user.target
