name: sync-aws-resources
on:
  push: [main]

env:
  AWS_REGION: us-east-1
  CLOUDFORMATION_ROLE_ARN: ${{ secrets.AWS_CLOUDFORMATION_ROLE_ARN }}
  SSH_KEY_NAME: ${{ secrets.AWS_SSH_KEY_NAME }}

  ENVIRONMENT: main
  NETWORK_STACK_NAME: minecraft-network-main
  EC2_TEMPLATES_STACK_NAME: minecraft-ec2templates-main

jobs:
  sync-aws-resources:
    name: sync aws resources
    runs-on: ubuntu-latest

    steps:
      - name: Checkout git repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy VPC networking foundation
        run: ./network/sync-resources.sh

      - name: Deploy EC2 Launch Templates
        run: ./templates/sync-resources.sh

      - name: Deploy Minecraft game servers
        run: ./servers/sync-resources.sh

      - name: Delete orphaned Minecraft game servers
        run: ./servers/destroy-resources.sh --only-orphans
